### PR TITLE
fix: make 2nd argument(routeDefinition) optional

### PR DESCRIPTION
**Pull request by mori5321**
Fixes: https://github.com/uhyo/rocon/issues/10

### CODE REVIEW

**Comment by mori5321** [comment]
I found my mistake and made PR draft.

**Comment by mori5321** [comment]
Could you please tell me your creating release build process? @uhyo 

### background
Since I would like to test this branch with my local React project, I need to build it by myself.

I just tried
```
1. run "npm run build" on "rocon"
2. run "npm install ~/local/rocon/path" on my local React project
```

But it does not seems to be sufficient, because an error was raised on Browser Console.
This might be because 'react' on devDependencies node_modules remains.

#### Error on Browser Console
```
react.development.js:1465 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

**Review by uhyo — APPROVED** [review]
Thank you very much!

**Comment by uhyo** [comment]
Regarding the local debugging, I have the following setting in my webback.config.js to avoid that problem.

```js
      alias: {
        react: path.join(__dirname, "node_modules/react"),
      },
```

We'd need more detailed contributing guides anyway 🙂

**Comment by mori5321** [comment]
@uhyo  Thx! I got it!

**Pull request merged**
